apiVersion: v1
kind: ConfigMap
metadata:
  name: cilium-config
  namespace: kube-system
data:
  cluster-name: k3s-ha
  cluster-id: "1"
  ipv4-native-routing-cidr: 10.42.0.0/16
  kube-proxy-replacement: strict
  enable-l7-proxy: "true"
