apiVersion: v1
kind: ConfigMap
metadata:
  name: antrea-config
  namespace: kube-system
data:
  antrea-agent.conf: |
    # Ajusta el modo de encapsulaci√≥n y los rangos usados por K3s
    trafficEncapMode: encap
    defaultMTU: 1450
    serviceCIDR: 10.43.0.0/16
  antrea-controller.conf: |
    featureGates:
      AntreaPolicy: true
