apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/flannel-io/flannel/v0.28.0/Documentation/kube-flannel.yml

patchesStrategicMerge:
  - patches/flannel-configmap-patch.yaml

configMapGenerator:
  - name: flannel-install-metadata
    literals:
      cni: flannel
      release: v0.24.2
      clusterNetworkCIDR: 10.42.0.0/16
      backend: vxlan

generatorOptions:
  disableNameSuffixHash: true
