apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/cilium/cilium/1.18.6/install/kubernetes/quick-install.yaml

patchesStrategicMerge:
  - patches/cilium-configmap-patch.yaml

configMapGenerator:
  - name: cilium-install-metadata
    literals:
      cni: cilium
      release: v1.18.6
      clusterNetworkCIDR: 10.42.0.0/16
      serviceCIDR: 10.43.0.0/16
      kubeProxyReplacement: strict

generatorOptions:
  disableNameSuffixHash: true
